mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nutrihub/', include('nutrihub.urls'))
]

mysite/nutrihub/urls.py
from django.urls import path, include
from . import views
from nutrihub import views as view

app_name = 'nutrihub'
urlpatterns = [
    path('home/', views.home_page, name='home'),
    path('map/',view.map, name="map"),
    path('get_foodbanks/', view.get_foodbanks, name='get_foodbanks'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('register_foodbank/', views.register_food_bank, name='register_foodbank'),
    path('make_donation/', views.make_a_donation, name='make_donation'),
    path('map/<int:zipcode>', view.map2, name='map2'),
    path('get_foodbanks/<int:zipcode>', view.get_foodbanks, name='get_foodbanks'),
    path('get_website/<str:place_id>', view.get_website, name = 'get_website'),
    # path('tutor/', include('tutor.urls')),
    # path('student/', include('student.urls')),
    # path('course/', views.tutor_search_courses, name='search'),
    # path('detail/', views.course_detail, name='course-detail'),
    # path('profile/', views.tutor_profile, name = 'tutor_profile')
    path('thank_you/', views.donate, name='thank_you'),
    path('request_food_bank/', views.make_a_request, name='make_request'),
    path('thank_you_request/', views.request_food_bank, name='thank_you_request')
]

mysite/nutrihub/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
# class User(models.Model):
#     username = models.CharField(max_length=150)  
#     email = models.EmailField()  
#     password1 = models.CharField(max_length=150)  
#     password2 = models.CharField(max_length=150)

class FoodBank(models.Model):
    name = models.CharField(max_length=500)
    address = models.CharField(max_length=1000)
    email = models.CharField(max_length=500)
    phone_number = models.CharField(max_length=10)
    donation_amount = models.FloatField(default=0)
    uses = models.IntegerField(default=0)

mysite/nutrihub/forms.py
from django import forms  
from django.contrib.auth import authenticate
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm  
from django.core.exceptions import ValidationError  
from django.forms.fields import EmailField  
from django.forms.forms import Form  
from .models import *
  
class CustomUserCreationForm(UserCreationForm):  
    username = forms.CharField(label='Username', min_length=5, max_length=150)  
    email = forms.EmailField(label='Email')  
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)  
  
    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return username  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError("Email Already Exist")  
        return email  
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        user.save()
        return user  


class RegisterFoodBankForm(forms.Form):
    name = forms.CharField(label='Enter your food bank name:', max_length=500)
    address = forms.CharField(label='Enter your address:', max_length=1000)
    email = forms.EmailField(label='Enter your email:', max_length=500)
    phone_number = forms.CharField(label='Enter your phone number:')


class SigninForm(AuthenticationForm):
    username = forms.CharField(label = 'Username')
    password = forms.CharField(label = 'Password', widget=forms.PasswordInput)

mysite/nutrihub/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from .models import *
from django import forms
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.contrib.auth import *
import time
import requests
from django.conf import settings
from django.http import JsonResponse
# from allauth.socialaccount import *
import time
import requests
from django.contrib.auth.forms import UserCreationForm  
from django.core.mail import send_mail
from .forms import *

import geocoder
import pgeocode
import json

def get_website(request, place_id):
    url = f'https://maps.googleapis.com/maps/api/place/details/json?place_id={place_id}&fields=website&key={settings.GOOGLE_API_KEY}'
    payload={}
    headers={}
    additionalinfo = requests.request("GET", url, headers = headers, data = payload)
    return HttpResponse(additionalinfo.text, content_type="application/json")

def get_foodbanks(request, zipcode):
    key = settings.GOOGLE_API_KEY

    g = geocoder.ip('me').latlng
    if(zipcode != 0):
        nomi = pgeocode.Nominatim('us')
        q = nomi.query_postal_code(str(zipcode))
        g = [q.latitude, q.longitude]
    elif(g is None):
        g = [38.0336, -78.5080]
    url = f'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={g[0]}%2C{g[1]}&radius=1500&keyword=food+bank&key={key}'
    payload={}
    headers = {}

    response = requests.request("GET", url, headers=headers, data=payload)
    return HttpResponse(response.text, content_type="application/json")

def get_foodbanks_list(zipcode):
    key = settings.GOOGLE_API_KEY

    g = geocoder.ip('me').latlng
    if(zipcode != 0):
        nomi = pgeocode.Nominatim('us')
        q = nomi.query_postal_code(str(zipcode))
        g = [q.latitude, q.longitude]
        print(g)
    elif(g is None):
        g = [38.0336, -78.5080]
    url = f'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={g[0]}%2C{g[1]}&radius=1500&keyword=food+bank&key={key}'
    payload={}
    headers = {}
    response = requests.request("GET", url, headers=headers, data=payload)

    response_json = json.loads(response.text)
    foodbank_list = []
    for foodbank in response_json["results"]:
        foodbank_list.append({"name": foodbank["name"], "vicinity": foodbank["vicinity"], "place_id": foodbank["place_id"]})    
    return foodbank_list

def map(request):
    key = settings.GOOGLE_API_KEY
    fb_dict = get_foodbanks_list(0)
    context = {
        'key':key,
        'fblist': fb_dict,
        'zipcode': 0
    }
    return render(request, 'nutrihub/map.html', context)

def map2(request, zipcode):
    # if ('search-input' in request.GET):
    #     zipcode = request['search-input']
    
    key = settings.GOOGLE_API_KEY
    fb_dict = get_foodbanks_list(zipcode)
    context = {
        'key':key,
        'fblist': fb_dict,
        'zipcode': zipcode
    }
    return render(request, 'nutrihub/map.html', context)

# Create your views here.
def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('nutrihub:home'))

def signin(request):  
    focus_signup = False
    print(request.POST)
    print(request.user)
    form = None
    signin = None

    if request.POST:
        print('post')
        if "email" in request.POST:
            form = CustomUserCreationForm(data=request.POST)
            if form.is_valid():
                print('save')  
                form.save()  
                user = authenticate(username=request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return map(request)
            else:
                focus_signup = True
        else:
            signin = SigninForm(data=request.POST)
            if signin.is_valid():
                user = authenticate(username=request.POST['username'], password=request.POST['password'])
                login(request, user)
                return map(request)
        # print(form.errors)
        # print(form.is_bound)
    if form is None:
        form = CustomUserCreationForm()
    if signin is None:
        signin = SigninForm()  
    context = {
        'form':form, 'signin':signin, 'focus_signup': focus_signup  
    }  
    return render(request, 'nutrihub/sign_in_up_page.html', context)  

def home_page(request):
    print(request.user)
    context = {'user': request.user, 'title': 'Home'}
    return render(request, "nutrihub/home_page.html", context)
# def signin(request):
#     context = {'user': request.user, 'title': 'Signin'}
#     return render(request, "nutrihub/sign_in_up_page.html", context)

def register_food_bank(request):
    if request.method == 'POST':
        if request.POST.get("save"):
            form = RegisterFoodBankForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data["name"]
                address = form.cleaned_data["address"]
                email = form.cleaned_data["email"]
                phone_number = form.cleaned_data["phone_number"]
                food_bank = FoodBank(name=name, address=address, email=email, phone_number=phone_number)
                food_bank.save()
    else:
        form = RegisterFoodBankForm()
    return render(request, 'nutrihub/foodbankregister.html', {'form': form})

def make_a_donation(request):
    food_banks = FoodBank.objects.all()
    return render(request, 'nutrihub/donation_page.html', {'food_banks':food_banks})

def donate(request):
    food_bank_id  = request.POST.get('selected_food_bank')
    print(food_bank_id)
    donated_amount = request.POST.get('donation')
    food_bank = FoodBank.objects.get(id=food_bank_id)
    current_donations = food_bank.donation_amount
    current_donations += float(donated_amount)
    food_bank.donation_amount = current_donations
    food_bank.save()
    return render(request, 'nutrihub/thank_you.html', {'food_bank': food_bank})

def make_a_request(request):
    food_banks = FoodBank.objects.all()
    return render(request, 'nutrihub/request.html', {'food_banks': food_banks})

def request_food_bank(request):
    food_bank_id = request.POST.get('selected_food_bank')
    writtenemail = request.POST.get('food_bank_request')
    food_bank = FoodBank.objects.get(id=food_bank_id)
    send_mail('Food Request', writtenemail + '\nEmail: ' + request.user.email, 'nutrihubber@gmail.com',[food_bank.email])
    return render(request, 'nutrihub/thank_you_request.html', {'food_bank': food_bank})

mysite/nutrihub/templates/nutrihub/base.html
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'google/main.css'%}"> -->
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>


    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!-- For formatting dates -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.21/sorting/datetime-moment.js"></script>

    <script type="text/javascript" src="//kit.fontawesome.com/b68b3cc9f2.js?ver=5.2.4"></script>
    <script src="https://kit.fontawesome.com/f44bd2967c.js" crossorigin="anonymous"></script>

    
    <title> Django - Google Maps API</title>

</head>
<body>
 
    {% block content %}
    {% endblock %}
 
</body>
</html>

mysite/nutrihub/templates/nutrihub/donation_page.html
{% load static %}

{% block styles %}
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static 'nutrihub/bootstrap.css' %}"/>
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Donation</title>
</head>

<style>
    .inv {
    display: none;
    }
</style>

<body>
    <nav class="navbar navbar-expand-lg py-0 navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="http://127.0.0.1:8000/nutrihub/home"><img src = "{% static 'nutrihub/logo.png' %}" class = "img-fluid" style ="width:40px;height: 40px;float:left;"><h3>Nutrihub</h3></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#contact">Contact Us</a>
              </li>
            </ul>
              <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/register_foodbank">
                <button class = "btn btn-info my-1 my-sm-1" type="submit">Register Food Bank</button>
            </form>
            <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/make_donation">
                <button class = "btn btn-warning my-1 my-sm-1" type="submit">Donate</button>
            </form>
            <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/request_food_bank">
                <button class = "btn btn-success my-1 my-sm-1" type="submit">Request</button>
            </form>
            {% if user.is_authenticated %}
            <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signout">
                <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign Out</button>
            </form>
            {% else %}
            <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signin">
                <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign In/Sign Up</button>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <br>

<div class="card text-white bg-secondary mb-3 mx-auto" style="max-width: 20rem;">
    <div class="card-header">Donate</div>
    <div class="card-body">
        <form action="{%url 'nutrihub:thank_you' %}" method="POST">
            {% csrf_token %}
        <label> Select a food bank </label>
            <br>
            <select id="target" onChange="getOption()">
            <option value="">Select...
            </option>
                {% for fb in food_banks %}
                    <option value = {{fb.id}}> {{fb.name}}
                    </option>
                {% endfor %}
            </select>
            <input type="hidden" id="food_bank" name="selected_food_bank">
        
            <br>
            <label>Enter the amount you would like to donate: </label>
            <input type="text" name="donation">
            <br>
            <br>
            <button class="btn btn-success" type="submit">Submit</button>
        </form>
    </div>

<script>
    function getOption(){
        var select = document.getElementById('target');
        var option = select.options[select.selectedIndex];

        document.getElementById('food_bank').value = option.value;
    }
</script>

</body>
</html>

mysite/nutrihub/templates/nutrihub/map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<style>
  .mapholder{
    height: 450px;
    width: 100%;
  }

  ul {
    list-style-type: none; /* Remove bullets */
    columns: 2;
    -webkit-columns: 2;
    -moz-columns: 2;
  }

  #map {
    height: 100%;
  }
</style>

<body>


{% extends 'nutrihub/base.html' %}
{% block content %}

{% load static %}
{% block styles %}


<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static 'nutrihub/bootstrap.css' %}"/>
{% endblock %}
<nav class="navbar navbar-expand-lg py-0 navbar-dark bg-primary">
  <div class="container-fluid">
      <a class="navbar-brand" href="http://127.0.0.1:8000/nutrihub/home"><img src = "{% static 'nutrihub/logo.png' %}" class = "img-fluid" style ="width:40px;height: 40px;float:left;"><h3>Nutrihub</h3></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav p-3 me-auto">
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#contact">Contact Us</a>
        </li>
      </ul>
      <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/register_foodbank">
                <button class = "btn btn-info my-1 my-sm-1" type="submit">Register Food Bank</button>
      </form>
      <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/make_donation">
          <button class = "btn btn-warning my-1 my-sm-1" type="submit">Donate</button>
      </form>
      <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/request_food_bank">
          <button class = "btn btn-success my-1 my-sm-1" type="submit">Request</button>
      </form>
      {% if user.is_authenticated %}
      <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signout">
          <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign Out</button>
      </form>
      {% else %}
      <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signin">
          <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign In/Sign Up</button>
        </form>
      {% endif %}
    </div>
  </div>
</nav>

<script>
    $(document).ready(function(){
        console.log("{{zipcode}}")
        var url = new URL("http://" + window.location.host + "/nutrihub/get_foodbanks/0")
        if ("{{zipcode}}" != 0){
            url = new URL("http://" + window.location.host + "/nutrihub/get_foodbanks/" + "{{zipcode}}")
            console.log("https://maps.googleapis.com/maps/api/geocode/json?address="+"{{zipcode}}"+'&key='+"{{key}}")
            fetch("https://maps.googleapis.com/maps/api/geocode/json?address="+"{{zipcode}}"+'&key='+"{{key}}")
              .then(response => response.json())
              .then(data1 => {
                $.ajax({
                    url: url,
                    method: 'GET',
                    success: function (data) { 
                      const pos = {
                        lat: data1.results[0].geometry.location.lat,
                        lng: data1.results[0].geometry.location.lng
                      };
                      initMap(data, pos)
                    }
                });
              })
        }
        else{
          $.ajax({
            url: url,
            method: 'GET',
            success: function (data) {
                navigator.geolocation.getCurrentPosition(
                  (position) => {
                    const pos = {
                      lat: position.coords.latitude,
                      lng: position.coords.longitude,
                    };
                    initMap(data, pos)
                });
            }
          });
        }
    });

    function initMap(data, pos) {
       const map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: {lat: pos.lat, lng: pos.lng}
       });
       const markers = data.results?.map((i) => {
            const marker = new google.maps.Marker({
                position: { lat: parseFloat(i.geometry.location.lat), lng: parseFloat(i.geometry.location.lng)},
                map: map,
                title: i.name + "\n" + i.vicinity
            })
        });
     }

     function get_website(place_id){
        console.log(place_id)
        const url = new URL("http://" + window.location.host + "/nutrihub/get_website/" + place_id)
          $.ajax({url: url, 
          method: 'GET',
          success: function (data) {
              const doc = document.getElementById("website+" + place_id)
              doc.innerHTML = data.result.website
              doc.setAttribute('href', data.result.website)
              document.getElementById(place_id).setAttribute('disabled')
            }
        });
     }
  </script>

<div>
  <div class="mapholder">
    <div id="map"></div>
    <script
    src="https://maps.googleapis.com/maps/api/js?key={{key}}&callback=initMap&v=weekly"
    defer
    ></script>
  </div>
</div>

<div><ul>
{% for fb in fblist %}
<li>
  <center><div class = "p-2 foodbank_list">
    <button class="btn btn-primary" id = "{{fb.place_id}}" onclick = "get_website('{{fb.place_id}}')">
      <p>{{fb.name}}</p>
      <p>{{fb.vicinity}}</p>
      <a id = "website+{{fb.place_id}}"></a>
    </button>
  </div></center>
  </li>
{% endfor %}
</ul>
</div>

<!-- <div>
  <form action="{% url 'nutrihub:map' %}" id="search-zip" method="GET">
    {% csrf_token %}
    <input type="text" id="search-input">
  </form>
</div> -->

{% endblock content %}
</body>
</html>

mysite/nutrihub/templates/nutrihub/request.html
{% load static %}

{% block styles %}
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static 'nutrihub/bootstrap.css' %}"/>
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Request</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg py-0 navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="http://127.0.0.1:8000/nutrihub/home"><img src = "{% static 'nutrihub/logo.png' %}" class = "img-fluid" style ="width:40px;height: 40px;float:left;"><h3>Nutrihub</h3></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#contact">Contact Us</a>
              </li>
            </ul>
              <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/register_foodbank">
                <button class = "btn btn-info my-1 my-sm-1" type="submit">Register Food Bank</button>
            </form>
            <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/make_donation">
                <button class = "btn btn-warning my-1 my-sm-1" type="submit">Donate</button>
            </form>
            <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/request_food_bank">
                <button class = "btn btn-success my-1 my-sm-1" type="submit">Request</button>
            </form>
            {% if user.is_authenticated %}
            <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signout">
                <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign Out</button>
            </form>
            {% else %}
            <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signin">
                <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign In/Sign Up</button>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <br>

<div class="card text-white bg-secondary mb-3 mx-auto" style="max-width: 20rem;">
    <div class="card-header">Request</div>
    <div class="card-body">
        <form action="{%url 'nutrihub:thank_you_request' %}" method="POST">
            {% csrf_token %}
        <label> Select a food bank </label>
            <br>
            <select id="target" onChange="getOption()">
            <option value="">Select...
            </option>
                {% for fb in food_banks %}
                    <option value = {{fb.id}}> {{fb.name}}
                    </option>
                {% endfor %}
            </select>
            <input type="hidden" id="food_bank" name="selected_food_bank">
        
            <br>
            <label>What are you requesting? </label>
            <textarea type="text" name="food_bank_request" placeholder="Please enter your request."></textarea>
            <br>
            <br>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>


<script>
    function getOption(){
        var select = document.getElementById('target');
        var option = select.options[select.selectedIndex];

        document.getElementById('food_bank').value = option.value;
    }
</script>

</body>
</html>

mysite/nutrihub/templates/nutrihub/thank_you.html
{% load static %}

{% block styles %}
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static 'nutrihub/bootstrap.css' %}"/>
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thank you</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg py-0 navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="http://127.0.0.1:8000/nutrihub/home"><img src = "{% static 'nutrihub/logo.png' %}" class = "img-fluid" style ="width:40px;height: 40px;float:left;"><h3>Nutrihub</h3></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/nutrihub/home/#contact">Contact Us</a>
              </li>
            </ul>
              <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/register_foodbank">
                <button class = "btn btn-info my-1 my-sm-1" type="submit">Register Food Bank</button>
            </form>
            <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/make_donation">
                <button class = "btn btn-warning my-1 my-sm-1" type="submit">Donate</button>
            </form>
            <form class="d-flex p-1" action="http://127.0.0.1:8000/nutrihub/request_food_bank">
                <button class = "btn btn-success my-1 my-sm-1" type="submit">Request</button>
            </form>
            {% if user.is_authenticated %}
            <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signout">
                <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign Out</button>
            </form>
            {% else %}
            <form class="d-flex" action="http://127.0.0.1:8000/nutrihub/signin">
                <button class = "btn btn-secondary my-2 my-sm-2" type="submit">Sign In/Sign Up</button>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <br>

    <div class="card text-white bg-secondary mb-3 mx-auto" style="max-width: 20rem;">
        <div class="card-header">Thank you!</div>
        <div class="card-body mx-auto">
            <form action="{%url 'nutrihub:map' %}">
                <p class="card-text">Thank you for your donation to {{ food_bank.name }}!</p>
                <button class="btn-primary btn" type="submit">Return Back to Map</button>
        </div>

</form>
</body>
</html>